### ISSUE TITLE
How can I use this in a workspace for the root `Cargo.toml`?

### ISSUE THREAD

**Issue by frederikhors** [rksm/cargo-add-dynamic#6]
How can I use this in a workspace for the root `Cargo.toml`?

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Found workspace but no target package. Please specify a package with --package.', C:\Users\fred\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-add-dynamic-0.1.2\src\main.rs:89:15
```

**Comment by rksm** [comment]
If you have a cargo workspace with a root package and you want to add a dynamic dependency to that root package, `cargo-add-dynamic <dependency>` will do it. If you want to add the dependency to one of the sub-packages in that workspace use `cargo-add-dynamic <dependency> --package <subpackage-name>`. Run `cargo-add-dynamic --help` to see the options.

**Comment by hamiltop** [comment]
This does not work as described.
```
cargo add-dynamic uom   
thread 'main' panicked at /Users/peterhamilton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-add-dynamic-0.1.2/src/main.rs:89:15:
called `Result::unwrap()` on an `Err` value: Found workspace but no target package. Please specify a package with --package.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
